name: Cross-compile

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest 
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cross
        run: cargo install cross
        
      - name: Build binary
        run: cross build --target ${{ matrix.target }} --release
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.target }}/release/
